[profile.default]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read-write", path = "./" }]

[profile.ci.fuzz]
runs = 10_000

[rpc_endpoints]
tenderly = "${RPC_TENDERLY}"
op_sepolia = "${RPC_OPTIMISM_SEPOLIA}"