[profile.default]
solc = "0.8.24"
evm_version = "cancun"
ffi = true
ast = true
via-ir = false
optimizer = true
optimizer-runs = 500
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read-write", path = "./" }]

[profile.lite]
optimizer = false

[profile.ci.fuzz]
runs = 10_000

[rpc_endpoints]
tenderly = "${RPC_TENDERLY}"
op_sepolia = "${RPC_OPTIMISM_SEPOLIA}"
polygon_amoy = "${RPC_POLYGON_AMOY}"

[lint]
lint_on_build = false