import { readFileSync } from "fs";
import { join } from "path";

/**
 * Ties the verifier sources in `src/verifiers/` to a specific trusted setup ceremony.
 *
 * A Groth16 verifying key has three parts with different origins: `alpha`/`beta` come from the
 * phase-1 powers of tau, the `IC` points come from the circuit's R1CS, and `delta` is the only
 * thing a phase-2 contribution changes. So a verifier left over from an earlier ceremony has the
 * correct public input count and the correct IC arity, and differs *only* in delta.
 *
 * That matters because every cheap sanity check misses it. Arity checks pass, the contract
 * compiles, deployment succeeds, proof generation succeeds, and the failure appears later as
 * `InvalidTransactionProof` from the pool, which reads as a contract bug rather than a stale file.
 * This exact mistake reached a deployed frontend: two circuits kept keys from the previous
 * ceremony and two more were copied into each other's directories, with nothing detecting it.
 *
 * The register verifier has a quieter variant. A stale five-input `VerifierRegister` still yields
 * 448 bytes of verifier calldata, so `Verifier._assertVParamsLength` passes, and the appended
 * registrant address is simply ignored as trailing calldata. Registration keeps working while the
 * front-running protection is inert, with no symptom at all.
 *
 * `script/ceremony-manifest.json` records the expected `deltax1`/`deltax2` and public input count
 * per verifier. Regenerate it whenever a new ceremony is run; see the README section in the PR
 * that introduced this file.
 */

type ManifestEntry = {
    deltax1: string;
    deltax2: string;
    publicInputs: number;
};

const MANIFEST_PATH = join(__dirname, "..", "ceremony-manifest.json");
const VERIFIERS_DIR = join(__dirname, "..", "..", "src", "verifiers");

/** Solidity verifiers are generated by snarkjs, so the constants are plain literals. */
const readConstants = (source: string): Record<string, string> => {
    const out: Record<string, string> = {};
    const re = /uint256 constant (\w+)\s*=\s*\n?\s*(\d+)/g;
    let m: RegExpExecArray | null;
    while ((m = re.exec(source)) !== null) {
        out[m[1]] = m[2];
    }
    return out;
};

/** Matches both `uint[N]` (as ejected) and `uint256[N]` (as committed). */
const readPublicInputCount = (source: string): number | undefined => {
    const m = source.match(/uint(?:256)?\[(\d+)\] calldata _pubSignals/);
    return m ? Number(m[1]) : undefined;
};

/**
 * Verifies every verifier named in the manifest against its source before any of them is deployed.
 * Pure: reads files only, touches no chain state.
 *
 * Deliberately checked at the source rather than after deployment, because the constants are
 * compile-time literals inlined into the bytecode with no getters to read them back. Hardhat
 * deploys the artifact compiled from these same sources, so pinning the source pins the bytecode.
 */
export const assertVerifiersMatchCeremony = () => {
    const manifest: Record<string, ManifestEntry> = JSON.parse(
        readFileSync(MANIFEST_PATH, "utf8")
    );

    const errors: string[] = [];

    for (const [name, expected] of Object.entries(manifest)) {
        let source: string;
        try {
            source = readFileSync(join(VERIFIERS_DIR, `${name}.sol`), "utf8");
        } catch {
            errors.push(`${name}.sol is in the ceremony manifest but missing from src/verifiers/`);
            continue;
        }

        const constants = readConstants(source);
        const publicInputs = readPublicInputCount(source);

        if (publicInputs !== expected.publicInputs) {
            errors.push(
                `${name} declares uint256[${publicInputs}] _pubSignals, manifest expects ` +
                `${expected.publicInputs} — this verifier was built from a different circuit revision`
            );
        }

        // delta is what identifies the ceremony. Both components, since a swap between two
        // circuits of the same shape would otherwise only shift one of them.
        if (constants.deltax1 !== expected.deltax1 || constants.deltax2 !== expected.deltax2) {
            errors.push(
                `${name} delta does not match the ceremony manifest — it is from a different ` +
                `phase-2 contribution.\n` +
                `      source   deltax1 ${constants.deltax1}\n` +
                `      manifest deltax1 ${expected.deltax1}`
            );
        }
    }

    if (errors.length > 0) {
        throw new Error(
            `Verifier sources do not match script/ceremony-manifest.json:\n` +
            errors.map((e) => `  - ${e}`).join("\n") +
            `\n\nNothing has been deployed. Either restore the ceremony's verifiers, or regenerate ` +
            `the manifest if this is intentionally a new ceremony.`
        );
    }

    console.log(
        `Verifiers match the ceremony manifest (${Object.keys(manifest).length} checked)`
    );
};
