// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;
import {Script} from "forge-std/Script.sol";
import {console2} from "forge-std/console2.sol";

contract AdaptorPayload is Script {
    function run() external pure {
        // This script is used to generate the payload for the adaptor.
        // It can be used to test the adaptor with different parameters.
        // The payload is generated by encoding the parameters in a specific format.
        // The payload can then be used in the adaptor's handleAssets function.
        bytes memory payload = abi.encode(
            uint24(65538), // outAssetId
            address(0), // beneficiary
            0 // minOut
        );
        console2.logBytes(payload);
    }
}
